#!/usr/bin/ruby

require_relative 'http/Response'

class ResponseFactory
    #  Call like a static method =  ResponseFactory.create(http_request, resource)
    def self.create(request, resource)
        # Build and return properly constructed repsonse.
        #resource.resolve

        # Handle request and resource.
        # Build and send response.
        Response.new(200, "Response generated by ResponseFactory.")
    end
end
